name: Deploy to EC2 (Apache+PHP)

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # フロントがあればビルド（無ければ丸ごと削除OK）
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build frontend (optional)
        run: |
          if [ -f package.json ]; then
            npm ci
            npm run build || true
          fi

      - name: Create artifact
        run: |
          tar -czf app.tar.gz \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            .

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Upload artifact
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" app.tar.gz \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/app.tar.gz

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOSSH'
          set -euo pipefail
          WEB_ROOT="${{ secrets.WEB_ROOT }}"
          TMPDIR="/tmp/deploy.$(date +%s)"
          mkdir -p "$TMPDIR"
          tar -xzf /tmp/app.tar.gz -C "$TMPDIR"

          # （任意）.env 差し込み
          if [ -n "${{ secrets.ENV_CONTENT }}" ]; then
            echo "${{ secrets.ENV_CONTENT }}" > "$TMPDIR/.env"
          fi

          # Apache配下に反映（ゼロダウンに寄せたいなら一時ディレクトリ→一括置換に）
          rsync -av --delete "$TMPDIR"/ "$WEB_ROOT"/

          # 権限（Apacheユーザーが apache or www-data。Amazon Linuxは apache が多い）
          if id apache >/dev/null 2>&1; then
            sudo chown -R apache:apache "$WEB_ROOT"
          elif id www-data >/dev/null 2>&1; then
            sudo chown -R www-data:www-data "$WEB_ROOT"
          fi
          sudo find "$WEB_ROOT" -type d -exec chmod 755 {} \;
          sudo find "$WEB_ROOT" -type f -exec chmod 644 {} \;

          # Apache/PHP再読み込み（環境により存在する方だけ成功）
          sudo systemctl reload httpd 2>/dev/null || true
          sudo systemctl reload apache2 2>/dev/null || true
          sudo systemctl reload php-fpm 2>/dev/null || true

          # お片付け
          rm -rf "$TMPDIR" /tmp/app.tar.gz
          echo "✅ Deploy done to $WEB_ROOT"
          EOSSH
