name: Deploy static site to EC2 (Apache)

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 秘密鍵をファイルに復元（SSH_KEY は pem の中身そのまま）
      - name: Write SSH key file
        run: |
          cat > /tmp/deploy_key <<'EOF'
          ${{ secrets.SSH_KEY }}
          EOF
          chmod 600 /tmp/deploy_key

      # まず -vvv で接続テスト（ここで原因が確定します）
      - name: SSH smoke test (-vvv)
        run: |
          ssh -vvv -i /tmp/deploy_key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'whoami'

      # /tmp/site に同期
      - name: Rsync to EC2 /tmp/site
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='.github' \
            -e "ssh -i /tmp/deploy_key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/site/

      # 公開ディレクトリへ反映
      - name: Publish to WEB_ROOT (no sudo)
        run: |
          ssh -i /tmp/deploy_key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOSSH'
          set -euo pipefail
          WEB_ROOT="${{ secrets.WEB_ROOT }}"
          rsync -av --delete /tmp/site/ "$WEB_ROOT"/
          echo "✅ Deploy done to $WEB_ROOT"
          EOSSH