name: Deploy static site to EC2 (Apache)

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1) 秘密鍵をagentへ
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # 2) 接続スモークテスト（ここで落ちたらユーザー名/鍵/ホストが違う）
      - name: SSH smoke test
        run: |
          ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'whoami'

      # 3) 一旦 /tmp/site に同期（sudo不要な場所）
      - name: Rsync to EC2 /tmp/site
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='.github' \
            -e "ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/site/

      # 4) 公開ディレクトリへ反映（sudoで移動・権限調整・reload）
        # WEB_ROOT は例: /var/www/html
      - name: Publish to WEB_ROOT
        run: |
          ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOSSH'
          set -euo pipefail
          WEB_ROOT="${{ secrets.WEB_ROOT }}"
          sudo rsync -av --delete /tmp/site/ "$WEB_ROOT"/

          # 権限（ディストリで自動判定）
          if id apache >/dev/null 2>&1; then
            sudo chown -R apache:apache "$WEB_ROOT"
          elif id www-data >/dev/null 2>&1; then
            sudo chown -R www-data:www-data "$WEB_ROOT"
          fi
          sudo find "$WEB_ROOT" -type d -exec chmod 755 {} \;
          sudo find "$WEB_ROOT" -type f -exec chmod 644 {} \;

          # Apache reload（ある方だけ効く）
          sudo systemctl reload httpd 2>/dev/null || sudo systemctl reload apache2 2>/dev/null || true

          echo "✅ Deploy done to $WEB_ROOT"
          EOSSH